# Copyright (c) 2016-2024 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: A comprehensive platform for Python training
site_url: https://saeidamiri1.github.io/python-training-platform/
site_author: Saeid Amiri
site_description:

# Repository
repo_name: saeidamiri1/python-training-platform
repo_url: https://github.com/saeidamiri1/python-training-platform

# Copyright
copyright: Copyright &copy; 2023 - 2024 Saeid Amiri

# Configuration
theme:
  name: material
  custom_dir: material/overrides
  icon:
    logo: material/language-python
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png

# Plugins
plugins:
  - mkdocs-jupyter:
        kernel_name: python3
        ignore_h1_titles: True
  - blog:
      blog_dir: concise_notes
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/saeidamiri1
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/saeid_amiri1

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  
not_in_nav: |
  /tutorials/**/*.md

# Page tree
nav:
  - Home: index.md
  - Book: 
      - "Overview": 'book/overview.md'
      - "Part I:":
        - "Chapter 1: Primer": 
            - "<b>Overview</b>":        'book/ch1_primer/ch1_overview.md'
            - "-- Primer":               book/ch1_primer/ch1_primer.md
            - "-- Module":               book/ch1_primer/ch1_module.md
            - "-- Scope and namespace":  book/ch1_primer/ch1_scope_and_namespace.md
            - "-- Editor":               book/ch1_primer/ch1_editor.md
            - "-- <em> Challenges</em>": book/ch1_primer/ch1_challenges.md            
        - "Chapter 2: Numpy": 
            - "<b>Overview</b>":         book/ch2_numpy/ch2_overview.md
            - "-- Numpy":                book/ch2_numpy/ch2_numpy.md
            - "-- <em> Challenges</em>": book/ch2_numpy/ch2_challenges.md
        - "Chapter 3:  Data analysis": 
            - "<b>Overview</b>":        'book/ch3_data_analysis/ch3_overview.md'
            - "-- Panda":                book/ch3_data_analysis/ch3_panda.md
            - "-- Working with time":    book/ch3_data_analysis/ch3_time.md
            - "-- Missing value":        book/ch3_data_analysis/ch3_missing.md
            - "-- <em> Challenges </em>": book/ch3_data_analysis/ch3_challengesipynb.ipynb
        - "Chapter 4: Visualization": 
            - "<b>Overview</b>":        'book/ch4_visualization/ch4_overview.md'
            - "-- Matplotlib":           book/ch4_visualization/ch4_matplotlib.md
            - "-- Seaborn":              book/ch4_visualization/ch4_seaborn.md
            - "-- Plotnine":             book/ch4_visualization/ch4_plotnine.md
            - "-- Boken":                book/ch4_visualization/ch4_boken.md
      - "Part II:": 
        - "Chapter 5: Working with files":
          - "<b>Overview</b>":           'book/ch5_file/file_overview.md'
          - "-- Text files":              book/ch5_file/file_file.md
          - "-- Storing objects":         book/ch5_file/file_pickle.md
          - "-- CSV":                     book/ch5_file/file_csv.md
          - "-- XLSX":                    book/ch5_file/file_xlsx.md
          - "-- <em> Challenges</em>":    book/ch5_file/file_challenges.md   
        - "Chapter 6: OS":
          - "<b>Overview</b>":            'book/ch6_os/os_overview.md'
          - "OS":                          book/ch6_os/os_os.md
          - "Subprocess":                  book/ch6_os/os_subprocess.md
          - "Sys":                         book/ch6_os/os_sys.md
          - "-- <em> Challenges</em>":     book/ch6_os/os_challenges.md   
        - "Chapter 7: Decorator":
          - "Decorator":                   book/ch7_decorator/decorator.md
        - "Chapter 8: Class":
          - "-- Class":                    book/ch8_class/class.md
          - "-- Inheritance":              book/ch8_class/inheritance.md
          - "-- Operator_overloading":     book/ch8_class/operator_overloading.md
          - "-- Class_as_decorators":      book/ch8_class/class_as_decorators.md
      - "Part III:": 
        - "Chapter 9: Scipy":
          - "-- Scipy":                    book/ch9_scipy/scipy.md
        - "Chapter 10: Functools": 
          - "<b>Overview</b>":            'book/ch10_functools/overview.md'
          - "-- functools":                book/ch10_functools/functools.md
          - "-- itertools":                book/ch10_functools/itertools.md
          - "-- generator":                book/ch10_functools/generator.md          
        - "Chapter 11: Parallel":
          - "-- Parallel":                 book/ch11_parallel/parallel.md
        - "Chapter 12: Regex":
          - "-- Regex":                    book/ch12_regex/regex.md
      - "Part IV:": 
        - "Chapter 13: Testing and debugging":
          - "<em>Overview</em>":          'book/ch13_debugging/overview.md'
          - '-- Error handling':          'book/ch13_debugging/error_handling.md'
          - "-- Loggin":                  "book/ch13_debugging/logging.md" 
          - "-- Debugging":               "book/ch13_debugging/debugging.md"
        - "Chapter 14: Package":
          - "<em>Overview</em>":          'book/ch14_package/overview.md'
          - "-- Package":                 "book/ch14_package/package.md" 
          - '-- Distribution':            'book/ch14_package/distribution.md'
        - "Chapter 15: Misc":
          - "-- Time":                     book/ch15_misc/time.md
          - "-- SQL":                      book/ch15_misc/sql.md
  - Python projects:
    - python_projects/overview.md
    - python_projects/posts/crime-mtl-pattern.md
    - python_projects/posts/optimization.md
  - Work shop:
      - "<b> Overview </b>": work_shop/README.md
      - "<b>Part I:</b>": 
        - "<b>1 Starting with data </b>": work_shop/notebooks/01-starting-with-data.ipynb
        - "<em>1 Exercise</em>": work_shop/exercises/01-exercise.ipynb 
        - "<b>2 Working with data </b>": work_shop/notebooks/02-working-with-data.ipynb
        - "<em>2 Exercise</em>": work_shop/exercises/02-exercise.ipynb 
        - "<b>3 Manipulating data frame </b>": work_shop/notebooks/03-manipulating-data-frame.ipynb 
        - "<em>3 Exercise</em>": work_shop/exercises/03-exercise.ipynb 
      - "<b> Part II: </b>":         
        - "<b>4 Summarizing </b>": work_shop/notebooks/04-summarizing.ipynb
        - "<em>1 Exercise</em>": work_shop/exercises/04-exercise.ipynb 
        - "<b>5 Merging data frame </b>": work_shop/notebooks/05-merging-data-frame.ipynb 
        - "<em>5 Exercise</em>": work_shop/exercises/05-exercise.ipynb 
        - "<b>6 Visualization </b>": work_shop/notebooks/06-visualization.ipynb
        - "<em>6 Exercise</em>": work_shop/exercises/06-exercise.ipynb 
  # - Note:
  #   - note/index.md
  #   - notes/posts/summarizing-data-frame.md
  #   - notes/posts/data-frame.md
  #   - notes/posts/data-control-structure.md
  #   - notes/posts/data-structure.md
  #   - notes/posts/applying-function-to-data-frame.md
  #   - notes/posts/cheatsheet-numpy-panda.md
  #   - notes/posts/cross-tabulate.md
  #   - notes/posts/cheatsheet_scikit.md
  #   - notes/posts/frequency-python.md
  #   - notes/posts/manipulating-data-frame.md
  #   - notes/posts/function-in-python.md
  #   - notes/posts/iteration.md
  #   - notes/posts/merging-dataframe.md
  #   - notes/posts/new-column-to-data-frame.md
  #   - notes/posts/plot.md
  #   - notes/posts/pipeline.md
  #   - notes/posts/generate_variable_in_loop.md
  #   - notes/posts/dill_dump.md
  #   - notes/posts/most_unique.md
  #   - notes/posts/apply_on_array.md
  - Concise notes:
    - concise_notes/index.md
    - concise_notes/posts/cheatsheet-numpy-panda.md
    - concise_notes/posts/cheatsheet_scikit.md
    - concise_notes/posts/plot.md
  # - Support:  support.md
